{
 "title": "Sochi - Temperature fluctuation",
 "description": "It was a pleasure to build this from scratch ;)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Mean Temperature, temperature measurements",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select ts_request as time,(raw_data->'current'->>'temp_c')::float as temp_c from \"data\".raw r "
    },
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  mean_temp\nFROM data.temp_change\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Current mean temperature",
   "type": "stat",
   "description": "Max of temperature at previous day",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select mean_temp\nfrom \"data\".temp_change tc \norder by date desc\nlimit 1;"
    }
   ]
  },
  {
   "title": "Max",
   "type": "stat",
   "description": "Max of temperature at previous day",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select max((raw_data->'current'->>'temp_c')::float ) as Max\nfrom \"data\".raw r \nwhere ts_request > current_date - interval '1' day;"
    }
   ]
  },
  {
   "title": "Min",
   "type": "stat",
   "description": "Min of temperature at previous day",
   "gridPos": { "h": 6, "w": 2, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select min((raw_data->'current'->>'temp_c')::float ) as Min\nfrom \"data\".raw r \nwhere ts_request > current_date - interval '1' day;"
    }
   ]
  },
  {
   "title": "10 min Mean temperature fluctuation",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  temp_fluct\nFROM data.temp_change\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Last hour mean temperature fluctuation",
   "type": "stat",
   "description": "Max of temperature at previous day",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select avg(temp_fluct)\nfrom \"data\".temp_change tc \nwhere \"date\" > (now() at time zone 'utc') - interval '1' hour;;"
    }
   ]
  },
  {
   "title": "number of actual measurements on location in 10 min",
   "type": "stat",
   "description": "Standard deviation of temperature at previous day",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct ts_location)\nfrom \"data\".raw \nwhere \"ts_location\" > (now() at time zone 'utc') - interval '10' minute;"
    }
   ]
  }
 ]
}